/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Derive, DeriveInterface } from "../Derive";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "a2",
        type: "uint256",
      },
    ],
    name: "test",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061021c806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063eb8ac92114610030575b600080fd5b61004a6004803603810190610045919061013a565b61004c565b005b610059617e44838361005d565b5050565b6100f783838360405160240161007593929190610189565b6040516020818303038152906040527fe7820a74000000000000000000000000000000000000000000000000000000007bffffffffffffffffffffffffffffffffffffffffffffffffffffffff19166020820180517bffffffffffffffffffffffffffffffffffffffffffffffffffffffff83818316178352505050506100fc565b505050565b60008151905060006a636f6e736f6c652e6c6f679050602083016000808483855afa5050505050565b600081359050610134816101cf565b92915050565b60008060408385031215610151576101506101ca565b5b600061015f85828601610125565b925050602061017085828601610125565b9150509250929050565b610183816101c0565b82525050565b600060608201905061019e600083018661017a565b6101ab602083018561017a565b6101b8604083018461017a565b949350505050565b6000819050919050565b600080fd5b6101d8816101c0565b81146101e357600080fd5b5056fea2646970667358221220a05e97959e4a99bb1a868667cd25af04876b6ed3fb9cb758ecbae88f90348b9564736f6c63430008070033";

export class Derive__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Derive> {
    return super.deploy(overrides || {}) as Promise<Derive>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Derive {
    return super.attach(address) as Derive;
  }
  connect(signer: Signer): Derive__factory {
    return super.connect(signer) as Derive__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DeriveInterface {
    return new utils.Interface(_abi) as DeriveInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Derive {
    return new Contract(address, _abi, signerOrProvider) as Derive;
  }
}
