/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HelperLibInterface extends ethers.utils.Interface {
  functions: {
    "getEventData(IStorage,uint256)": FunctionFragment;
    "getEventManagers(IStorage,uint256)": FunctionFragment;
    "getEventTickets(IStorage,uint256[])": FunctionFragment;
    "getEvents(IStorage,uint256[])": FunctionFragment;
    "getSingleEntityArray(uint256)": FunctionFragment;
    "getTicketData(IStorage,uint256)": FunctionFragment;
    "getTicketUsdMaticPrice(IStorage,AggregatorV3Interface,uint256)": FunctionFragment;
    "getTickets(IStorage,uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getEventData",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventManagers",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventTickets",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvents",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getSingleEntityArray",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketData",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketUsdMaticPrice",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTickets",
    values: [string, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEventData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSingleEntityArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketUsdMaticPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTickets", data: BytesLike): Result;

  events: {};
}

export class HelperLib extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HelperLibInterface;

  functions: {
    getEventData(
      _storage: string,
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [string, string, string[], BigNumber[]] & {
          organizer: string;
          beneficiary: string;
          managers: string[];
          ticketIds: BigNumber[];
        }
      ]
    >;

    getEventManagers(
      _storage: string,
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getEventTickets(
      _storage: string,
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          eventTokenId: BigNumber;
          params: BigNumber;
          price: BigNumber;
          supply: BigNumber;
          subscriptionDuration: BigNumber;
          subscriptionActivatedAt: BigNumber;
          tier: BigNumber;
        })[][]
      ]
    >;

    getEvents(
      _storage: string,
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, string[], BigNumber[]] & {
          organizer: string;
          beneficiary: string;
          managers: string[];
          ticketIds: BigNumber[];
        })[]
      ]
    >;

    "getSingleEntityArray(uint256)"(
      _uint: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    "getSingleEntityArray(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getTicketData(
      _storage: string,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          eventTokenId: BigNumber;
          params: BigNumber;
          price: BigNumber;
          supply: BigNumber;
          subscriptionDuration: BigNumber;
          subscriptionActivatedAt: BigNumber;
          tier: BigNumber;
        }
      ]
    >;

    getTicketUsdMaticPrice(
      _storage: string,
      priceFeed: string,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTickets(
      _storage: string,
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          eventTokenId: BigNumber;
          params: BigNumber;
          price: BigNumber;
          supply: BigNumber;
          subscriptionDuration: BigNumber;
          subscriptionActivatedAt: BigNumber;
          tier: BigNumber;
        })[]
      ]
    >;
  };

  getEventData(
    _storage: string,
    eventId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, string, string[], BigNumber[]] & {
      organizer: string;
      beneficiary: string;
      managers: string[];
      ticketIds: BigNumber[];
    }
  >;

  getEventManagers(
    _storage: string,
    eventId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getEventTickets(
    _storage: string,
    eventIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      eventTokenId: BigNumber;
      params: BigNumber;
      price: BigNumber;
      supply: BigNumber;
      subscriptionDuration: BigNumber;
      subscriptionActivatedAt: BigNumber;
      tier: BigNumber;
    })[][]
  >;

  getEvents(
    _storage: string,
    eventIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([string, string, string[], BigNumber[]] & {
      organizer: string;
      beneficiary: string;
      managers: string[];
      ticketIds: BigNumber[];
    })[]
  >;

  "getSingleEntityArray(uint256)"(
    _uint: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  "getSingleEntityArray(address)"(
    _address: string,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getTicketData(
    _storage: string,
    ticketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      eventTokenId: BigNumber;
      params: BigNumber;
      price: BigNumber;
      supply: BigNumber;
      subscriptionDuration: BigNumber;
      subscriptionActivatedAt: BigNumber;
      tier: BigNumber;
    }
  >;

  getTicketUsdMaticPrice(
    _storage: string,
    priceFeed: string,
    ticketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTickets(
    _storage: string,
    ticketIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      eventTokenId: BigNumber;
      params: BigNumber;
      price: BigNumber;
      supply: BigNumber;
      subscriptionDuration: BigNumber;
      subscriptionActivatedAt: BigNumber;
      tier: BigNumber;
    })[]
  >;

  callStatic: {
    getEventData(
      _storage: string,
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, string, string[], BigNumber[]] & {
        organizer: string;
        beneficiary: string;
        managers: string[];
        ticketIds: BigNumber[];
      }
    >;

    getEventManagers(
      _storage: string,
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getEventTickets(
      _storage: string,
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        eventTokenId: BigNumber;
        params: BigNumber;
        price: BigNumber;
        supply: BigNumber;
        subscriptionDuration: BigNumber;
        subscriptionActivatedAt: BigNumber;
        tier: BigNumber;
      })[][]
    >;

    getEvents(
      _storage: string,
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([string, string, string[], BigNumber[]] & {
        organizer: string;
        beneficiary: string;
        managers: string[];
        ticketIds: BigNumber[];
      })[]
    >;

    "getSingleEntityArray(uint256)"(
      _uint: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    "getSingleEntityArray(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getTicketData(
      _storage: string,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        eventTokenId: BigNumber;
        params: BigNumber;
        price: BigNumber;
        supply: BigNumber;
        subscriptionDuration: BigNumber;
        subscriptionActivatedAt: BigNumber;
        tier: BigNumber;
      }
    >;

    getTicketUsdMaticPrice(
      _storage: string,
      priceFeed: string,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTickets(
      _storage: string,
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        eventTokenId: BigNumber;
        params: BigNumber;
        price: BigNumber;
        supply: BigNumber;
        subscriptionDuration: BigNumber;
        subscriptionActivatedAt: BigNumber;
        tier: BigNumber;
      })[]
    >;
  };

  filters: {};

  estimateGas: {
    getEventData(
      _storage: string,
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEventManagers(
      _storage: string,
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEventTickets(
      _storage: string,
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEvents(
      _storage: string,
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSingleEntityArray(uint256)"(
      _uint: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getSingleEntityArray(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTicketData(
      _storage: string,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTicketUsdMaticPrice(
      _storage: string,
      priceFeed: string,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTickets(
      _storage: string,
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getEventData(
      _storage: string,
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEventManagers(
      _storage: string,
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEventTickets(
      _storage: string,
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEvents(
      _storage: string,
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSingleEntityArray(uint256)"(
      _uint: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getSingleEntityArray(address)"(
      _address: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTicketData(
      _storage: string,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTicketUsdMaticPrice(
      _storage: string,
      priceFeed: string,
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTickets(
      _storage: string,
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
