/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IStorageInterface extends ethers.utils.Interface {
  functions: {
    "addUint(bytes32,uint256)": FunctionFragment;
    "confirmGuardian()": FunctionFragment;
    "deleteAddress(bytes32)": FunctionFragment;
    "deleteAddressArray(bytes32,uint256)": FunctionFragment;
    "deleteBool(bytes32)": FunctionFragment;
    "deleteBoolArray(bytes32,uint256)": FunctionFragment;
    "deleteBytes(bytes32)": FunctionFragment;
    "deleteBytes32(bytes32)": FunctionFragment;
    "deleteBytes32Array(bytes32,uint256)": FunctionFragment;
    "deleteBytesArray(bytes32,uint256)": FunctionFragment;
    "deleteInt(bytes32)": FunctionFragment;
    "deleteIntArray(bytes32,uint256)": FunctionFragment;
    "deleteString(bytes32)": FunctionFragment;
    "deleteStringArray(bytes32,uint256)": FunctionFragment;
    "deleteUint(bytes32)": FunctionFragment;
    "deleteUintArray(bytes32,uint256)": FunctionFragment;
    "getAddress(bytes32)": FunctionFragment;
    "getAddressArray(bytes32)": FunctionFragment;
    "getBool(bytes32)": FunctionFragment;
    "getBoolArray(bytes32)": FunctionFragment;
    "getBytes(bytes32)": FunctionFragment;
    "getBytes32(bytes32)": FunctionFragment;
    "getBytes32Array(bytes32)": FunctionFragment;
    "getBytesArray(bytes32)": FunctionFragment;
    "getDeployedStatus()": FunctionFragment;
    "getGuardian()": FunctionFragment;
    "getInt(bytes32)": FunctionFragment;
    "getIntArray(bytes32)": FunctionFragment;
    "getString(bytes32)": FunctionFragment;
    "getStringArray(bytes32)": FunctionFragment;
    "getUint(bytes32)": FunctionFragment;
    "getUintArray(bytes32)": FunctionFragment;
    "setAddress(bytes32,address)": FunctionFragment;
    "setAddressArray(bytes32,address[])": FunctionFragment;
    "setBool(bytes32,bool)": FunctionFragment;
    "setBoolArray(bytes32,bool[])": FunctionFragment;
    "setBytes(bytes32,bytes)": FunctionFragment;
    "setBytes32(bytes32,bytes32)": FunctionFragment;
    "setBytes32Array(bytes32,bytes32[])": FunctionFragment;
    "setBytesArray(bytes32,bytes[])": FunctionFragment;
    "setGuardian(address)": FunctionFragment;
    "setInt(bytes32,int256)": FunctionFragment;
    "setIntArray(bytes32,int256[])": FunctionFragment;
    "setString(bytes32,string)": FunctionFragment;
    "setStringArray(bytes32,string[])": FunctionFragment;
    "setUint(bytes32,uint256)": FunctionFragment;
    "setUintArray(bytes32,uint256[])": FunctionFragment;
    "subUint(bytes32,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deleteAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteAddressArray",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBoolArray",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytes",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytes32Array",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteBytesArray",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteInt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteIntArray",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteStringArray",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteUint",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteUintArray",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddressArray",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getBool", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBoolArray",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getBytes", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getBytes32",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBytes32Array",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBytesArray",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeployedStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGuardian",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getInt", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getIntArray",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getString",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStringArray",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getUint", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getUintArray",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressArray",
    values: [BytesLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setBool",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setBoolArray",
    values: [BytesLike, boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes32",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytes32Array",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytesArray",
    values: [BytesLike, BytesLike[]]
  ): string;
  encodeFunctionData(functionFragment: "setGuardian", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setInt",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setIntArray",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setString",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setStringArray",
    values: [BytesLike, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setUint",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUintArray",
    values: [BytesLike, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "subUint",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confirmGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteAddressArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteBool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteBoolArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytes32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytes32Array",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteBytesArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteInt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteIntArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteStringArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deleteUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteUintArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddressArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBoolArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBytes32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBytes32Array",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBytesArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDeployedStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getInt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIntArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getString", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStringArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUintArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddressArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBoolArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBytes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setBytes32", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBytes32Array",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBytesArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGuardian",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setInt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIntArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setString", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStringArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setUint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setUintArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subUint", data: BytesLike): Result;

  events: {};
}

export class IStorage extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IStorageInterface;

  functions: {
    addUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    confirmGuardian(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteAddress(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteAddressArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteBool(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteBoolArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteBytes(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteBytes32(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteBytes32Array(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteBytesArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteInt(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteIntArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteString(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteStringArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteUint(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deleteUintArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getAddress(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getAddressArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getBool(_key: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    getBoolArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean[]]>;

    getBytes(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getBytes32Array(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getBytesArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getDeployedStatus(overrides?: CallOverrides): Promise<[boolean]>;

    getGuardian(overrides?: CallOverrides): Promise<[string]>;

    getInt(_key: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    getIntArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    getString(_key: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getStringArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getUint(_key: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

    getUintArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    setAddress(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAddressArray(
      _key: BytesLike,
      _value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBool(
      _key: BytesLike,
      _value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBoolArray(
      _key: BytesLike,
      _value: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBytes(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBytes32(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBytes32Array(
      _key: BytesLike,
      _value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setBytesArray(
      _key: BytesLike,
      _value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGuardian(
      _newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setInt(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setIntArray(
      _key: BytesLike,
      _value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setString(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setStringArray(
      _key: BytesLike,
      _value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUint(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setUintArray(
      _key: BytesLike,
      _value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    subUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  addUint(
    _key: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  confirmGuardian(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteAddress(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteAddressArray(
    _key: BytesLike,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteBool(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteBoolArray(
    _key: BytesLike,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteBytes(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteBytes32(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteBytes32Array(
    _key: BytesLike,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteBytesArray(
    _key: BytesLike,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteInt(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteIntArray(
    _key: BytesLike,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteString(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteStringArray(
    _key: BytesLike,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteUint(
    _key: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deleteUintArray(
    _key: BytesLike,
    index: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getAddress(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  getAddressArray(
    _key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getBool(_key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  getBoolArray(_key: BytesLike, overrides?: CallOverrides): Promise<boolean[]>;

  getBytes(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  getBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  getBytes32Array(
    _key: BytesLike,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getBytesArray(_key: BytesLike, overrides?: CallOverrides): Promise<string[]>;

  getDeployedStatus(overrides?: CallOverrides): Promise<boolean>;

  getGuardian(overrides?: CallOverrides): Promise<string>;

  getInt(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  getIntArray(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber[]>;

  getString(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

  getStringArray(_key: BytesLike, overrides?: CallOverrides): Promise<string[]>;

  getUint(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

  getUintArray(
    _key: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  setAddress(
    _key: BytesLike,
    _value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAddressArray(
    _key: BytesLike,
    _value: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBool(
    _key: BytesLike,
    _value: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBoolArray(
    _key: BytesLike,
    _value: boolean[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBytes(
    _key: BytesLike,
    _value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBytes32(
    _key: BytesLike,
    _value: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBytes32Array(
    _key: BytesLike,
    _value: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setBytesArray(
    _key: BytesLike,
    _value: BytesLike[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGuardian(
    _newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setInt(
    _key: BytesLike,
    _value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setIntArray(
    _key: BytesLike,
    _value: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setString(
    _key: BytesLike,
    _value: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setStringArray(
    _key: BytesLike,
    _value: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUint(
    _key: BytesLike,
    _value: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setUintArray(
    _key: BytesLike,
    _value: BigNumberish[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  subUint(
    _key: BytesLike,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    confirmGuardian(overrides?: CallOverrides): Promise<void>;

    deleteAddress(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteAddressArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteBool(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteBoolArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteBytes(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteBytes32Array(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteBytesArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteInt(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteIntArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteString(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteStringArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deleteUint(_key: BytesLike, overrides?: CallOverrides): Promise<void>;

    deleteUintArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getAddress(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    getAddressArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getBool(_key: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    getBoolArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean[]>;

    getBytes(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    getBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    getBytes32Array(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getBytesArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getDeployedStatus(overrides?: CallOverrides): Promise<boolean>;

    getGuardian(overrides?: CallOverrides): Promise<string>;

    getInt(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getIntArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    getString(_key: BytesLike, overrides?: CallOverrides): Promise<string>;

    getStringArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getUint(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getUintArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    setAddress(
      _key: BytesLike,
      _value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setAddressArray(
      _key: BytesLike,
      _value: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setBool(
      _key: BytesLike,
      _value: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setBoolArray(
      _key: BytesLike,
      _value: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    setBytes(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setBytes32(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setBytes32Array(
      _key: BytesLike,
      _value: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    setBytesArray(
      _key: BytesLike,
      _value: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    setGuardian(_newAddress: string, overrides?: CallOverrides): Promise<void>;

    setInt(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setIntArray(
      _key: BytesLike,
      _value: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    setString(
      _key: BytesLike,
      _value: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setStringArray(
      _key: BytesLike,
      _value: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    setUint(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setUintArray(
      _key: BytesLike,
      _value: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    subUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    addUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    confirmGuardian(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteAddress(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteAddressArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteBool(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteBoolArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteBytes(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteBytes32(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteBytes32Array(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteBytesArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteInt(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteIntArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteString(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteStringArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteUint(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deleteUintArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getAddress(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getAddressArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBool(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getBoolArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBytes(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getBytes32(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getBytes32Array(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getBytesArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getDeployedStatus(overrides?: CallOverrides): Promise<BigNumber>;

    getGuardian(overrides?: CallOverrides): Promise<BigNumber>;

    getInt(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getIntArray(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getString(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getStringArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getUint(_key: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    getUintArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setAddress(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAddressArray(
      _key: BytesLike,
      _value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBool(
      _key: BytesLike,
      _value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBoolArray(
      _key: BytesLike,
      _value: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBytes(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBytes32(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBytes32Array(
      _key: BytesLike,
      _value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setBytesArray(
      _key: BytesLike,
      _value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGuardian(
      _newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setInt(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setIntArray(
      _key: BytesLike,
      _value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setString(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setStringArray(
      _key: BytesLike,
      _value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUint(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setUintArray(
      _key: BytesLike,
      _value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    subUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    confirmGuardian(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteAddress(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteAddressArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteBool(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteBoolArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteBytes(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteBytes32(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteBytes32Array(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteBytesArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteInt(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteIntArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteString(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteStringArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteUint(
      _key: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deleteUintArray(
      _key: BytesLike,
      index: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getAddress(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAddressArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBool(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBoolArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBytes(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBytes32(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBytes32Array(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getBytesArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getDeployedStatus(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getGuardian(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getInt(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getIntArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getString(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStringArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUint(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getUintArray(
      _key: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setAddress(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAddressArray(
      _key: BytesLike,
      _value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBool(
      _key: BytesLike,
      _value: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBoolArray(
      _key: BytesLike,
      _value: boolean[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBytes(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBytes32(
      _key: BytesLike,
      _value: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBytes32Array(
      _key: BytesLike,
      _value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setBytesArray(
      _key: BytesLike,
      _value: BytesLike[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGuardian(
      _newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setInt(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setIntArray(
      _key: BytesLike,
      _value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setString(
      _key: BytesLike,
      _value: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setStringArray(
      _key: BytesLike,
      _value: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUint(
      _key: BytesLike,
      _value: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setUintArray(
      _key: BytesLike,
      _value: BigNumberish[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    subUint(
      _key: BytesLike,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
