/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MainTESTV9Interface extends ethers.utils.Interface {
  functions: {
    "TICKET_BOUGHT_BIT()": FunctionFragment;
    "TICKET_SPENT_BIT()": FunctionFragment;
    "TICKET_TIER_EARLYBIRD_BIT()": FunctionFragment;
    "TICKET_TIER_OFFLINE_BIT()": FunctionFragment;
    "TICKET_TIER_ONLINE_BIT()": FunctionFragment;
    "TICKET_TIER_SUBSCRIPTION_BIT()": FunctionFragment;
    "TICKET_TIER_TEAM_BIT()": FunctionFragment;
    "TICKET_TIER_UNLIMITED_SUPPLY_BIT()": FunctionFragment;
    "buyTickets(uint256,uint256,address[])": FunctionFragment;
    "createEvent((uint256[],uint256[],uint256[],address,address[],string,string[]))": FunctionFragment;
    "getEventManagers(uint256)": FunctionFragment;
    "getEventTicketTiers(uint256)": FunctionFragment;
    "getEventTickets(uint256[])": FunctionFragment;
    "getEvents(uint256[])": FunctionFragment;
    "getFeeCollector()": FunctionFragment;
    "getFeeRate()": FunctionFragment;
    "getOwnedEventTicket(address,uint256)": FunctionFragment;
    "getSlippageRate()": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "initializeV2()": FunctionFragment;
    "initializeV3()": FunctionFragment;
    "initializeV4()": FunctionFragment;
    "initializeV5()": FunctionFragment;
    "initializeV6()": FunctionFragment;
    "initializeV7()": FunctionFragment;
    "initializeV8()": FunctionFragment;
    "initializeV9()": FunctionFragment;
    "name()": FunctionFragment;
    "owner()": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setContractName(string)": FunctionFragment;
    "setEventTicketMetadata(uint256,uint256,string)": FunctionFragment;
    "setEventTicketSupply(uint256,uint256,uint256)": FunctionFragment;
    "setEventTicketTierPrice(uint256,uint256,uint256)": FunctionFragment;
    "setFeeCollector(address)": FunctionFragment;
    "setFeeRate(uint8)": FunctionFragment;
    "setSlippageRate(uint8)": FunctionFragment;
    "setTokenContract(address)": FunctionFragment;
    "spendTickets(uint256,uint256[],address[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "version()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "TICKET_BOUGHT_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICKET_SPENT_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICKET_TIER_EARLYBIRD_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICKET_TIER_OFFLINE_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICKET_TIER_ONLINE_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICKET_TIER_SUBSCRIPTION_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICKET_TIER_TEAM_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TICKET_TIER_UNLIMITED_SUPPLY_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyTickets",
    values: [BigNumberish, BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createEvent",
    values: [
      {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        ticketParams: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventManagers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventTicketTiers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventTickets",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvents",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnedEventTicket",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSlippageRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV5",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV6",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV7",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV8",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initializeV9",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setContractName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setEventTicketMetadata",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setEventTicketSupply",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEventTicketTierPrice",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlippageRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "spendTickets",
    values: [BigNumberish, BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "TICKET_BOUGHT_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICKET_SPENT_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICKET_TIER_EARLYBIRD_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICKET_TIER_OFFLINE_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICKET_TIER_ONLINE_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICKET_TIER_SUBSCRIPTION_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICKET_TIER_TEAM_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TICKET_TIER_UNLIMITED_SUPPLY_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyTickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventTicketTiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFeeRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOwnedEventTicket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSlippageRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initializeV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV5",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV6",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV7",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initializeV9",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setContractName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEventTicketMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEventTicketSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEventTicketTierPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSlippageRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "spendTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "EventCreated(uint256,address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TicketBought(uint256,uint256,address,uint256)": EventFragment;
    "TicketSpent(uint256,uint256,address,uint256)": EventFragment;
    "TicketTierCreated(uint256,uint256)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EventCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketBought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketSpent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketTierCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export type AdminChangedEvent = TypedEvent<
  [string, string] & { previousAdmin: string; newAdmin: string }
>;

export type BeaconUpgradedEvent = TypedEvent<[string] & { beacon: string }>;

export type EventCreatedEvent = TypedEvent<
  [BigNumber, string] & { eventTokenId: BigNumber; organizer: string }
>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type TicketBoughtEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber] & {
    eventTokenId: BigNumber;
    ticketTokenId: BigNumber;
    ticketOwner: string;
    ticketTierId: BigNumber;
  }
>;

export type TicketSpentEvent = TypedEvent<
  [BigNumber, BigNumber, string, BigNumber] & {
    eventTokenId: BigNumber;
    ticketTokenId: BigNumber;
    ticketOwner: string;
    ticketTierId: BigNumber;
  }
>;

export type TicketTierCreatedEvent = TypedEvent<
  [BigNumber, BigNumber] & { eventTokenId: BigNumber; ticketTierId: BigNumber }
>;

export type UpgradedEvent = TypedEvent<[string] & { implementation: string }>;

export class MainTESTV9 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MainTESTV9Interface;

  functions: {
    TICKET_BOUGHT_BIT(overrides?: CallOverrides): Promise<[number]>;

    TICKET_SPENT_BIT(overrides?: CallOverrides): Promise<[number]>;

    TICKET_TIER_EARLYBIRD_BIT(overrides?: CallOverrides): Promise<[number]>;

    TICKET_TIER_OFFLINE_BIT(overrides?: CallOverrides): Promise<[number]>;

    TICKET_TIER_ONLINE_BIT(overrides?: CallOverrides): Promise<[number]>;

    TICKET_TIER_SUBSCRIPTION_BIT(overrides?: CallOverrides): Promise<[number]>;

    TICKET_TIER_TEAM_BIT(overrides?: CallOverrides): Promise<[number]>;

    TICKET_TIER_UNLIMITED_SUPPLY_BIT(
      overrides?: CallOverrides
    ): Promise<[number]>;

    buyTickets(
      eventTokenId: BigNumberish,
      ticketTierId: BigNumberish,
      _for: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        ticketParams: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getEventManagers(
      eventTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getEventTicketTiers(
      eventTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          string
        ] & {
          eventTokenId: BigNumber;
          ticketParams: BigNumber;
          ticketPrice: BigNumber;
          ticketSupply: BigNumber;
          ticketsSoldAmount: BigNumber;
          tier: BigNumber;
          metadataUri: string;
        })[]
      ]
    >;

    getEventTickets(
      ticketTokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([BigNumber, BigNumber, BigNumber, BigNumber, string] & {
          eventTokenId: BigNumber;
          params: BigNumber;
          price: BigNumber;
          tier: BigNumber;
          owner: string;
        })[]
      ]
    >;

    getEvents(
      eventTokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, string[]] & {
          organizer: string;
          beneficiary: string;
          managers: string[];
        })[]
      ]
    >;

    getFeeCollector(overrides?: CallOverrides): Promise<[string]>;

    getFeeRate(overrides?: CallOverrides): Promise<[number]>;

    getOwnedEventTicket(
      ticketOwner: string,
      ticketTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, BigNumber, string] & {
          eventTokenId: BigNumber;
          params: BigNumber;
          price: BigNumber;
          tier: BigNumber;
          owner: string;
        }
      ]
    >;

    getSlippageRate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      storageAddress: string,
      chainlinkPriceAggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeV2(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeV3(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeV4(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeV5(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeV6(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeV7(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeV8(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initializeV9(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    name(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setContractName(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setEventTicketMetadata(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      metadataUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setEventTicketSupply(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      supply: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setEventTicketTierPrice(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeeCollector(
      newFeeCollector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeeRate(
      newFeeRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSlippageRate(
      newSlippageRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    spendTickets(
      eventTokenId: BigNumberish,
      ticketTokenIds: BigNumberish[],
      ticketOwners: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[number]>;
  };

  TICKET_BOUGHT_BIT(overrides?: CallOverrides): Promise<number>;

  TICKET_SPENT_BIT(overrides?: CallOverrides): Promise<number>;

  TICKET_TIER_EARLYBIRD_BIT(overrides?: CallOverrides): Promise<number>;

  TICKET_TIER_OFFLINE_BIT(overrides?: CallOverrides): Promise<number>;

  TICKET_TIER_ONLINE_BIT(overrides?: CallOverrides): Promise<number>;

  TICKET_TIER_SUBSCRIPTION_BIT(overrides?: CallOverrides): Promise<number>;

  TICKET_TIER_TEAM_BIT(overrides?: CallOverrides): Promise<number>;

  TICKET_TIER_UNLIMITED_SUPPLY_BIT(overrides?: CallOverrides): Promise<number>;

  buyTickets(
    eventTokenId: BigNumberish,
    ticketTierId: BigNumberish,
    _for: string[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createEvent(
    payload: {
      ticketSupply: BigNumberish[];
      ticketPrice: BigNumberish[];
      ticketParams: BigNumberish[];
      beneficiary: string;
      managers: string[];
      eventMetadataUri: string;
      ticketMetadataUri: string[];
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getEventManagers(
    eventTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getEventTicketTiers(
    eventTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    ([
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      string
    ] & {
      eventTokenId: BigNumber;
      ticketParams: BigNumber;
      ticketPrice: BigNumber;
      ticketSupply: BigNumber;
      ticketsSoldAmount: BigNumber;
      tier: BigNumber;
      metadataUri: string;
    })[]
  >;

  getEventTickets(
    ticketTokenIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([BigNumber, BigNumber, BigNumber, BigNumber, string] & {
      eventTokenId: BigNumber;
      params: BigNumber;
      price: BigNumber;
      tier: BigNumber;
      owner: string;
    })[]
  >;

  getEvents(
    eventTokenIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([string, string, string[]] & {
      organizer: string;
      beneficiary: string;
      managers: string[];
    })[]
  >;

  getFeeCollector(overrides?: CallOverrides): Promise<string>;

  getFeeRate(overrides?: CallOverrides): Promise<number>;

  getOwnedEventTicket(
    ticketOwner: string,
    ticketTokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, BigNumber, string] & {
      eventTokenId: BigNumber;
      params: BigNumber;
      price: BigNumber;
      tier: BigNumber;
      owner: string;
    }
  >;

  getSlippageRate(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    storageAddress: string,
    chainlinkPriceAggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeV2(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeV3(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeV4(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeV5(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeV6(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeV7(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeV8(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initializeV9(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  name(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setContractName(
    _name: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setEventTicketMetadata(
    eventTokenId: BigNumberish,
    ticketTier: BigNumberish,
    metadataUri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setEventTicketSupply(
    eventTokenId: BigNumberish,
    ticketTier: BigNumberish,
    supply: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setEventTicketTierPrice(
    eventTokenId: BigNumberish,
    ticketTier: BigNumberish,
    price: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeeCollector(
    newFeeCollector: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeeRate(
    newFeeRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSlippageRate(
    newSlippageRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenContract(
    tokenContractAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  spendTickets(
    eventTokenId: BigNumberish,
    ticketTokenIds: BigNumberish[],
    ticketOwners: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    TICKET_BOUGHT_BIT(overrides?: CallOverrides): Promise<number>;

    TICKET_SPENT_BIT(overrides?: CallOverrides): Promise<number>;

    TICKET_TIER_EARLYBIRD_BIT(overrides?: CallOverrides): Promise<number>;

    TICKET_TIER_OFFLINE_BIT(overrides?: CallOverrides): Promise<number>;

    TICKET_TIER_ONLINE_BIT(overrides?: CallOverrides): Promise<number>;

    TICKET_TIER_SUBSCRIPTION_BIT(overrides?: CallOverrides): Promise<number>;

    TICKET_TIER_TEAM_BIT(overrides?: CallOverrides): Promise<number>;

    TICKET_TIER_UNLIMITED_SUPPLY_BIT(
      overrides?: CallOverrides
    ): Promise<number>;

    buyTickets(
      eventTokenId: BigNumberish,
      ticketTierId: BigNumberish,
      _for: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        ticketParams: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: CallOverrides
    ): Promise<void>;

    getEventManagers(
      eventTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getEventTicketTiers(
      eventTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      ([
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        string
      ] & {
        eventTokenId: BigNumber;
        ticketParams: BigNumber;
        ticketPrice: BigNumber;
        ticketSupply: BigNumber;
        ticketsSoldAmount: BigNumber;
        tier: BigNumber;
        metadataUri: string;
      })[]
    >;

    getEventTickets(
      ticketTokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([BigNumber, BigNumber, BigNumber, BigNumber, string] & {
        eventTokenId: BigNumber;
        params: BigNumber;
        price: BigNumber;
        tier: BigNumber;
        owner: string;
      })[]
    >;

    getEvents(
      eventTokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([string, string, string[]] & {
        organizer: string;
        beneficiary: string;
        managers: string[];
      })[]
    >;

    getFeeCollector(overrides?: CallOverrides): Promise<string>;

    getFeeRate(overrides?: CallOverrides): Promise<number>;

    getOwnedEventTicket(
      ticketOwner: string,
      ticketTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber, string] & {
        eventTokenId: BigNumber;
        params: BigNumber;
        price: BigNumber;
        tier: BigNumber;
        owner: string;
      }
    >;

    getSlippageRate(overrides?: CallOverrides): Promise<number>;

    initialize(
      storageAddress: string,
      chainlinkPriceAggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initializeV2(overrides?: CallOverrides): Promise<void>;

    initializeV3(overrides?: CallOverrides): Promise<void>;

    initializeV4(overrides?: CallOverrides): Promise<void>;

    initializeV5(overrides?: CallOverrides): Promise<void>;

    initializeV6(overrides?: CallOverrides): Promise<void>;

    initializeV7(overrides?: CallOverrides): Promise<void>;

    initializeV8(overrides?: CallOverrides): Promise<void>;

    initializeV9(overrides?: CallOverrides): Promise<void>;

    name(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setContractName(_name: string, overrides?: CallOverrides): Promise<void>;

    setEventTicketMetadata(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      metadataUri: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setEventTicketSupply(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      supply: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setEventTicketTierPrice(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      price: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeCollector(
      newFeeCollector: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeRate(
      newFeeRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSlippageRate(
      newSlippageRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    spendTickets(
      eventTokenId: BigNumberish,
      ticketTokenIds: BigNumberish[],
      ticketOwners: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<number>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    BeaconUpgraded(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    "EventCreated(uint256,address)"(
      eventTokenId?: BigNumberish | null,
      organizer?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { eventTokenId: BigNumber; organizer: string }
    >;

    EventCreated(
      eventTokenId?: BigNumberish | null,
      organizer?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { eventTokenId: BigNumber; organizer: string }
    >;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "TicketBought(uint256,uint256,address,uint256)"(
      eventTokenId?: BigNumberish | null,
      ticketTokenId?: BigNumberish | null,
      ticketOwner?: string | null,
      ticketTierId?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      {
        eventTokenId: BigNumber;
        ticketTokenId: BigNumber;
        ticketOwner: string;
        ticketTierId: BigNumber;
      }
    >;

    TicketBought(
      eventTokenId?: BigNumberish | null,
      ticketTokenId?: BigNumberish | null,
      ticketOwner?: string | null,
      ticketTierId?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      {
        eventTokenId: BigNumber;
        ticketTokenId: BigNumber;
        ticketOwner: string;
        ticketTierId: BigNumber;
      }
    >;

    "TicketSpent(uint256,uint256,address,uint256)"(
      eventTokenId?: BigNumberish | null,
      ticketTokenId?: BigNumberish | null,
      ticketOwner?: string | null,
      ticketTierId?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      {
        eventTokenId: BigNumber;
        ticketTokenId: BigNumber;
        ticketOwner: string;
        ticketTierId: BigNumber;
      }
    >;

    TicketSpent(
      eventTokenId?: BigNumberish | null,
      ticketTokenId?: BigNumberish | null,
      ticketOwner?: string | null,
      ticketTierId?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string, BigNumber],
      {
        eventTokenId: BigNumber;
        ticketTokenId: BigNumber;
        ticketOwner: string;
        ticketTierId: BigNumber;
      }
    >;

    "TicketTierCreated(uint256,uint256)"(
      eventTokenId?: BigNumberish | null,
      ticketTierId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { eventTokenId: BigNumber; ticketTierId: BigNumber }
    >;

    TicketTierCreated(
      eventTokenId?: BigNumberish | null,
      ticketTierId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { eventTokenId: BigNumber; ticketTierId: BigNumber }
    >;

    "Upgraded(address)"(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;

    Upgraded(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;
  };

  estimateGas: {
    TICKET_BOUGHT_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    TICKET_SPENT_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    TICKET_TIER_EARLYBIRD_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    TICKET_TIER_OFFLINE_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    TICKET_TIER_ONLINE_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    TICKET_TIER_SUBSCRIPTION_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    TICKET_TIER_TEAM_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    TICKET_TIER_UNLIMITED_SUPPLY_BIT(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    buyTickets(
      eventTokenId: BigNumberish,
      ticketTierId: BigNumberish,
      _for: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        ticketParams: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getEventManagers(
      eventTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEventTicketTiers(
      eventTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEventTickets(
      ticketTokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEvents(
      eventTokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeeCollector(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeRate(overrides?: CallOverrides): Promise<BigNumber>;

    getOwnedEventTicket(
      ticketOwner: string,
      ticketTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSlippageRate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      storageAddress: string,
      chainlinkPriceAggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeV2(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeV3(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeV4(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeV5(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeV6(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeV7(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeV8(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initializeV9(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setContractName(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setEventTicketMetadata(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      metadataUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setEventTicketSupply(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      supply: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setEventTicketTierPrice(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeeCollector(
      newFeeCollector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeeRate(
      newFeeRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSlippageRate(
      newSlippageRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    spendTickets(
      eventTokenId: BigNumberish,
      ticketTokenIds: BigNumberish[],
      ticketOwners: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    TICKET_BOUGHT_BIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TICKET_SPENT_BIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    TICKET_TIER_EARLYBIRD_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TICKET_TIER_OFFLINE_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TICKET_TIER_ONLINE_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TICKET_TIER_SUBSCRIPTION_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TICKET_TIER_TEAM_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    TICKET_TIER_UNLIMITED_SUPPLY_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    buyTickets(
      eventTokenId: BigNumberish,
      ticketTierId: BigNumberish,
      _for: string[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        ticketParams: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getEventManagers(
      eventTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEventTicketTiers(
      eventTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEventTickets(
      ticketTokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEvents(
      eventTokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeeCollector(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeeRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOwnedEventTicket(
      ticketOwner: string,
      ticketTokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSlippageRate(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      storageAddress: string,
      chainlinkPriceAggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeV2(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeV3(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeV4(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeV5(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeV6(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeV7(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeV8(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initializeV9(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setContractName(
      _name: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setEventTicketMetadata(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      metadataUri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setEventTicketSupply(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      supply: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setEventTicketTierPrice(
      eventTokenId: BigNumberish,
      ticketTier: BigNumberish,
      price: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeeCollector(
      newFeeCollector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeeRate(
      newFeeRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSlippageRate(
      newSlippageRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    spendTickets(
      eventTokenId: BigNumberish,
      ticketTokenIds: BigNumberish[],
      ticketOwners: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
