/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MainInterface extends ethers.utils.Interface {
  functions: {
    "DEFAULT_ADMIN_ROLE()": FunctionFragment;
    "IS_INFINITE_SUPPLY()": FunctionFragment;
    "IS_SUBSCRIPTION()": FunctionFragment;
    "buyTickets(uint256,address)": FunctionFragment;
    "commitVerifiedTickets(uint256,uint256[],address[])": FunctionFragment;
    "createEvent((uint256[],uint256[],uint256[],uint256[],address,address[],string,string[]))": FunctionFragment;
    "events(uint256)": FunctionFragment;
    "getEventManagers(uint256)": FunctionFragment;
    "getEventTickets(uint256[])": FunctionFragment;
    "getEvents(uint256[])": FunctionFragment;
    "getRoleAdmin(bytes32)": FunctionFragment;
    "getTicketUsdMaticPrice(uint256)": FunctionFragment;
    "getTickets(uint256[])": FunctionFragment;
    "grantRole(bytes32,address)": FunctionFragment;
    "hasRole(bytes32,address)": FunctionFragment;
    "prolongSubscription(uint256)": FunctionFragment;
    "renounceRole(bytes32,address)": FunctionFragment;
    "revokeRole(bytes32,address)": FunctionFragment;
    "setTokenContract(address)": FunctionFragment;
    "supportsInterface(bytes4)": FunctionFragment;
    "tickets(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IS_INFINITE_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IS_SUBSCRIPTION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyTickets",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "commitVerifiedTickets",
    values: [BigNumberish, BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createEvent",
    values: [
      {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "events",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventManagers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventTickets",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvents",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTicketUsdMaticPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTickets",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "prolongSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tickets",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IS_INFINITE_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IS_SUBSCRIPTION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyTickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitVerifiedTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "events", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getEventManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTicketUsdMaticPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTickets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "prolongSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tickets", data: BytesLike): Result;

  events: {
    "EventCreated(uint256,address)": EventFragment;
    "RoleAdminChanged(bytes32,bytes32,bytes32)": EventFragment;
    "RoleGranted(bytes32,address,address)": EventFragment;
    "RoleRevoked(bytes32,address,address)": EventFragment;
    "TicketBought(uint256,uint256,address)": EventFragment;
    "TicketUsed(uint256,uint256,address)": EventFragment;
    "TicketsCreated(uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "EventCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleAdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleGranted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RoleRevoked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketBought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketUsed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketsCreated"): EventFragment;
}

export type EventCreatedEvent = TypedEvent<
  [BigNumber, string] & { tokenId: BigNumber; organizer: string }
>;

export type RoleAdminChangedEvent = TypedEvent<
  [string, string, string] & {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
>;

export type RoleGrantedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type RoleRevokedEvent = TypedEvent<
  [string, string, string] & { role: string; account: string; sender: string }
>;

export type TicketBoughtEvent = TypedEvent<
  [BigNumber, BigNumber, string] & {
    eventTokenId: BigNumber;
    tokenId: BigNumber;
    buyer: string;
  }
>;

export type TicketUsedEvent = TypedEvent<
  [BigNumber, BigNumber, string] & {
    tokenId: BigNumber;
    eventTokenId: BigNumber;
    owner: string;
  }
>;

export type TicketsCreatedEvent = TypedEvent<
  [BigNumber, BigNumber] & { tokenId: BigNumber; eventTokenId: BigNumber }
>;

export class Main extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MainInterface;

  functions: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<[string]>;

    IS_INFINITE_SUPPLY(overrides?: CallOverrides): Promise<[BigNumber]>;

    IS_SUBSCRIPTION(overrides?: CallOverrides): Promise<[BigNumber]>;

    buyTickets(
      ticketId: BigNumberish,
      _for: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    commitVerifiedTickets(
      eventTokenId: BigNumberish,
      ticketIds: BigNumberish[],
      owners: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    events(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { organizer: string; beneficiary: string }>;

    getEventManagers(
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getEventTickets(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          boolean,
          BigNumber,
          BigNumber
        ] & {
          eventTokenId: BigNumber;
          ticketType: BigNumber;
          price: BigNumber;
          supply: BigNumber;
          isInfiniteSupply: BigNumber;
          duration: BigNumber;
          used: boolean;
          activatedAt: BigNumber;
          tier: BigNumber;
        })[][]
      ]
    >;

    getEvents(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, string[], BigNumber[]] & {
          organizer: string;
          beneficiary: string;
          managers: string[];
          ticketIds: BigNumber[];
        })[]
      ]
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<[string]>;

    getTicketUsdMaticPrice(
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getTickets(
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          boolean,
          BigNumber,
          BigNumber
        ] & {
          eventTokenId: BigNumber;
          ticketType: BigNumber;
          price: BigNumber;
          supply: BigNumber;
          isInfiniteSupply: BigNumber;
          duration: BigNumber;
          used: boolean;
          activatedAt: BigNumber;
          tier: BigNumber;
        })[]
      ]
    >;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    prolongSubscription(
      ticketId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    tickets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        BigNumber,
        BigNumber
      ] & {
        eventTokenId: BigNumber;
        ticketType: BigNumber;
        price: BigNumber;
        supply: BigNumber;
        isInfiniteSupply: BigNumber;
        duration: BigNumber;
        used: boolean;
        activatedAt: BigNumber;
        tier: BigNumber;
      }
    >;
  };

  DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

  IS_INFINITE_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

  IS_SUBSCRIPTION(overrides?: CallOverrides): Promise<BigNumber>;

  buyTickets(
    ticketId: BigNumberish,
    _for: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  commitVerifiedTickets(
    eventTokenId: BigNumberish,
    ticketIds: BigNumberish[],
    owners: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createEvent(
    payload: {
      ticketSupply: BigNumberish[];
      ticketPrice: BigNumberish[];
      subscriptionDuration: BigNumberish[];
      params: BigNumberish[];
      beneficiary: string;
      managers: string[];
      eventMetadataUri: string;
      ticketMetadataUri: string[];
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  events(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, string] & { organizer: string; beneficiary: string }>;

  getEventManagers(
    eventId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getEventTickets(
    eventIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean,
      BigNumber,
      BigNumber
    ] & {
      eventTokenId: BigNumber;
      ticketType: BigNumber;
      price: BigNumber;
      supply: BigNumber;
      isInfiniteSupply: BigNumber;
      duration: BigNumber;
      used: boolean;
      activatedAt: BigNumber;
      tier: BigNumber;
    })[][]
  >;

  getEvents(
    eventIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([string, string, string[], BigNumber[]] & {
      organizer: string;
      beneficiary: string;
      managers: string[];
      ticketIds: BigNumber[];
    })[]
  >;

  getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

  getTicketUsdMaticPrice(
    ticketId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTickets(
    ticketIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean,
      BigNumber,
      BigNumber
    ] & {
      eventTokenId: BigNumber;
      ticketType: BigNumber;
      price: BigNumber;
      supply: BigNumber;
      isInfiniteSupply: BigNumber;
      duration: BigNumber;
      used: boolean;
      activatedAt: BigNumber;
      tier: BigNumber;
    })[]
  >;

  grantRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  hasRole(
    role: BytesLike,
    account: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  prolongSubscription(
    ticketId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeRole(
    role: BytesLike,
    account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenContract(
    tokenContractAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  supportsInterface(
    interfaceId: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  tickets(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      boolean,
      BigNumber,
      BigNumber
    ] & {
      eventTokenId: BigNumber;
      ticketType: BigNumber;
      price: BigNumber;
      supply: BigNumber;
      isInfiniteSupply: BigNumber;
      duration: BigNumber;
      used: boolean;
      activatedAt: BigNumber;
      tier: BigNumber;
    }
  >;

  callStatic: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<string>;

    IS_INFINITE_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    IS_SUBSCRIPTION(overrides?: CallOverrides): Promise<BigNumber>;

    buyTickets(
      ticketId: BigNumberish,
      _for: string,
      overrides?: CallOverrides
    ): Promise<void>;

    commitVerifiedTickets(
      eventTokenId: BigNumberish,
      ticketIds: BigNumberish[],
      owners: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: CallOverrides
    ): Promise<void>;

    events(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, string] & { organizer: string; beneficiary: string }>;

    getEventManagers(
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getEventTickets(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        BigNumber,
        BigNumber
      ] & {
        eventTokenId: BigNumber;
        ticketType: BigNumber;
        price: BigNumber;
        supply: BigNumber;
        isInfiniteSupply: BigNumber;
        duration: BigNumber;
        used: boolean;
        activatedAt: BigNumber;
        tier: BigNumber;
      })[][]
    >;

    getEvents(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([string, string, string[], BigNumber[]] & {
        organizer: string;
        beneficiary: string;
        managers: string[];
        ticketIds: BigNumber[];
      })[]
    >;

    getRoleAdmin(role: BytesLike, overrides?: CallOverrides): Promise<string>;

    getTicketUsdMaticPrice(
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTickets(
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        BigNumber,
        BigNumber
      ] & {
        eventTokenId: BigNumber;
        ticketType: BigNumber;
        price: BigNumber;
        supply: BigNumber;
        isInfiniteSupply: BigNumber;
        duration: BigNumber;
        used: boolean;
        activatedAt: BigNumber;
        tier: BigNumber;
      })[]
    >;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    prolongSubscription(
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    tickets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        boolean,
        BigNumber,
        BigNumber
      ] & {
        eventTokenId: BigNumber;
        ticketType: BigNumber;
        price: BigNumber;
        supply: BigNumber;
        isInfiniteSupply: BigNumber;
        duration: BigNumber;
        used: boolean;
        activatedAt: BigNumber;
        tier: BigNumber;
      }
    >;
  };

  filters: {
    "EventCreated(uint256,address)"(
      tokenId?: BigNumberish | null,
      organizer?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { tokenId: BigNumber; organizer: string }
    >;

    EventCreated(
      tokenId?: BigNumberish | null,
      organizer?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { tokenId: BigNumber; organizer: string }
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)"(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    RoleAdminChanged(
      role?: BytesLike | null,
      previousAdminRole?: BytesLike | null,
      newAdminRole?: BytesLike | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; previousAdminRole: string; newAdminRole: string }
    >;

    "RoleGranted(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleGranted(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "RoleRevoked(bytes32,address,address)"(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    RoleRevoked(
      role?: BytesLike | null,
      account?: string | null,
      sender?: string | null
    ): TypedEventFilter<
      [string, string, string],
      { role: string; account: string; sender: string }
    >;

    "TicketBought(uint256,uint256,address)"(
      eventTokenId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { eventTokenId: BigNumber; tokenId: BigNumber; buyer: string }
    >;

    TicketBought(
      eventTokenId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { eventTokenId: BigNumber; tokenId: BigNumber; buyer: string }
    >;

    "TicketUsed(uint256,uint256,address)"(
      tokenId?: BigNumberish | null,
      eventTokenId?: BigNumberish | null,
      owner?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { tokenId: BigNumber; eventTokenId: BigNumber; owner: string }
    >;

    TicketUsed(
      tokenId?: BigNumberish | null,
      eventTokenId?: BigNumberish | null,
      owner?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { tokenId: BigNumber; eventTokenId: BigNumber; owner: string }
    >;

    "TicketsCreated(uint256,uint256)"(
      tokenId?: BigNumberish | null,
      eventTokenId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { tokenId: BigNumber; eventTokenId: BigNumber }
    >;

    TicketsCreated(
      tokenId?: BigNumberish | null,
      eventTokenId?: BigNumberish | null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { tokenId: BigNumber; eventTokenId: BigNumber }
    >;
  };

  estimateGas: {
    DEFAULT_ADMIN_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    IS_INFINITE_SUPPLY(overrides?: CallOverrides): Promise<BigNumber>;

    IS_SUBSCRIPTION(overrides?: CallOverrides): Promise<BigNumber>;

    buyTickets(
      ticketId: BigNumberish,
      _for: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    commitVerifiedTickets(
      eventTokenId: BigNumberish,
      ticketIds: BigNumberish[],
      owners: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    events(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    getEventManagers(
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEventTickets(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEvents(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTicketUsdMaticPrice(
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTickets(
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    prolongSubscription(
      ticketId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    tickets(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    DEFAULT_ADMIN_ROLE(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    IS_INFINITE_SUPPLY(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    IS_SUBSCRIPTION(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyTickets(
      ticketId: BigNumberish,
      _for: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    commitVerifiedTickets(
      eventTokenId: BigNumberish,
      ticketIds: BigNumberish[],
      owners: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    events(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEventManagers(
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEventTickets(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEvents(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRoleAdmin(
      role: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTicketUsdMaticPrice(
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTickets(
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    grantRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    hasRole(
      role: BytesLike,
      account: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    prolongSubscription(
      ticketId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeRole(
      role: BytesLike,
      account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    supportsInterface(
      interfaceId: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    tickets(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
