/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface MainInterface extends ethers.utils.Interface {
  functions: {
    "INFINITE_SUPPLY_TICKET_BIT()": FunctionFragment;
    "OFFLINE_TICKET_TYPE_BIT()": FunctionFragment;
    "ONLINE_TICKET_TYPE_BIT()": FunctionFragment;
    "SUBSCRIPTION_TICKET_TYPE_BIT()": FunctionFragment;
    "USED_TICKET_BIT()": FunctionFragment;
    "buyTickets(uint256,address)": FunctionFragment;
    "commitVerifiedTickets(uint256,uint256[],address[])": FunctionFragment;
    "createEvent((uint256[],uint256[],uint256[],uint256[],address,address[],string,string[]))": FunctionFragment;
    "getEventManagers(uint256)": FunctionFragment;
    "getEventTickets(uint256[])": FunctionFragment;
    "getEvents(uint256[])": FunctionFragment;
    "getFeeCollector()": FunctionFragment;
    "getFeeRate()": FunctionFragment;
    "getTickets(uint256[])": FunctionFragment;
    "initialize(address,address)": FunctionFragment;
    "owner()": FunctionFragment;
    "prolongSubscription(uint256)": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setFeeCollector(address)": FunctionFragment;
    "setFeeRate(uint8)": FunctionFragment;
    "setSlippageRate(uint8)": FunctionFragment;
    "setTokenContract(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
    "upgradeToAndCall(address,bytes)": FunctionFragment;
    "version()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "INFINITE_SUPPLY_TICKET_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "OFFLINE_TICKET_TYPE_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ONLINE_TICKET_TYPE_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "SUBSCRIPTION_TICKET_TYPE_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "USED_TICKET_BIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "buyTickets",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "commitVerifiedTickets",
    values: [BigNumberish, BigNumberish[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "createEvent",
    values: [
      {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventManagers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEventTickets",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvents",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTickets",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "prolongSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeCollector",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlippageRate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenContract",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "INFINITE_SUPPLY_TICKET_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "OFFLINE_TICKET_TYPE_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ONLINE_TICKET_TYPE_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "SUBSCRIPTION_TICKET_TYPE_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "USED_TICKET_BIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "buyTickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitVerifiedTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEventTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFeeRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getTickets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "prolongSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFeeRate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSlippageRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;

  events: {
    "AdminChanged(address,address)": EventFragment;
    "BeaconUpgraded(address)": EventFragment;
    "EventCreated(uint256,address)": EventFragment;
    "Initialized(uint8)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "TicketBought(uint256,uint256,address)": EventFragment;
    "TicketUsed(uint256,uint256,address)": EventFragment;
    "TicketsCreated(uint256,uint256,address)": EventFragment;
    "Upgraded(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminChanged"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "BeaconUpgraded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "EventCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Initialized"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketBought"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketUsed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TicketsCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Upgraded"): EventFragment;
}

export type AdminChangedEvent = TypedEvent<
  [string, string] & { previousAdmin: string; newAdmin: string }
>;

export type BeaconUpgradedEvent = TypedEvent<[string] & { beacon: string }>;

export type EventCreatedEvent = TypedEvent<
  [BigNumber, string] & { tokenId: BigNumber; organizer: string }
>;

export type InitializedEvent = TypedEvent<[number] & { version: number }>;

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export type TicketBoughtEvent = TypedEvent<
  [BigNumber, BigNumber, string] & {
    eventTokenId: BigNumber;
    tokenId: BigNumber;
    buyer: string;
  }
>;

export type TicketUsedEvent = TypedEvent<
  [BigNumber, BigNumber, string] & {
    tokenId: BigNumber;
    eventTokenId: BigNumber;
    owner: string;
  }
>;

export type TicketsCreatedEvent = TypedEvent<
  [BigNumber, BigNumber, string] & {
    tokenId: BigNumber;
    eventTokenId: BigNumber;
    organizer: string;
  }
>;

export type UpgradedEvent = TypedEvent<[string] & { implementation: string }>;

export class Main extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MainInterface;

  functions: {
    INFINITE_SUPPLY_TICKET_BIT(overrides?: CallOverrides): Promise<[number]>;

    OFFLINE_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<[number]>;

    ONLINE_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<[number]>;

    SUBSCRIPTION_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<[number]>;

    USED_TICKET_BIT(overrides?: CallOverrides): Promise<[number]>;

    buyTickets(
      ticketId: BigNumberish,
      _for: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    commitVerifiedTickets(
      eventTokenId: BigNumberish,
      ticketIds: BigNumberish[],
      owners: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getEventManagers(
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getEventTickets(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          eventTokenId: BigNumber;
          params: BigNumber;
          price: BigNumber;
          supply: BigNumber;
          subscriptionDuration: BigNumber;
          subscriptionActivatedAt: BigNumber;
          tier: BigNumber;
        })[][]
      ]
    >;

    getEvents(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, string, string[], BigNumber[]] & {
          organizer: string;
          beneficiary: string;
          managers: string[];
          ticketIds: BigNumber[];
        })[]
      ]
    >;

    getFeeCollector(overrides?: CallOverrides): Promise<[string]>;

    getFeeRate(overrides?: CallOverrides): Promise<[number]>;

    getTickets(
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      [
        ([
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber,
          BigNumber
        ] & {
          eventTokenId: BigNumber;
          params: BigNumber;
          price: BigNumber;
          supply: BigNumber;
          subscriptionDuration: BigNumber;
          subscriptionActivatedAt: BigNumber;
          tier: BigNumber;
        })[]
      ]
    >;

    initialize(
      storageAddress: string,
      chainlinkPriceAggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    prolongSubscription(
      ticketId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeeCollector(
      newFeeCollector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setFeeRate(
      newFeeRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSlippageRate(
      newSlippageRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    version(overrides?: CallOverrides): Promise<[number]>;
  };

  INFINITE_SUPPLY_TICKET_BIT(overrides?: CallOverrides): Promise<number>;

  OFFLINE_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<number>;

  ONLINE_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<number>;

  SUBSCRIPTION_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<number>;

  USED_TICKET_BIT(overrides?: CallOverrides): Promise<number>;

  buyTickets(
    ticketId: BigNumberish,
    _for: string,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  commitVerifiedTickets(
    eventTokenId: BigNumberish,
    ticketIds: BigNumberish[],
    owners: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createEvent(
    payload: {
      ticketSupply: BigNumberish[];
      ticketPrice: BigNumberish[];
      subscriptionDuration: BigNumberish[];
      params: BigNumberish[];
      beneficiary: string;
      managers: string[];
      eventMetadataUri: string;
      ticketMetadataUri: string[];
    },
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getEventManagers(
    eventId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getEventTickets(
    eventIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      eventTokenId: BigNumber;
      params: BigNumber;
      price: BigNumber;
      supply: BigNumber;
      subscriptionDuration: BigNumber;
      subscriptionActivatedAt: BigNumber;
      tier: BigNumber;
    })[][]
  >;

  getEvents(
    eventIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([string, string, string[], BigNumber[]] & {
      organizer: string;
      beneficiary: string;
      managers: string[];
      ticketIds: BigNumber[];
    })[]
  >;

  getFeeCollector(overrides?: CallOverrides): Promise<string>;

  getFeeRate(overrides?: CallOverrides): Promise<number>;

  getTickets(
    ticketIds: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    ([
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber,
      BigNumber
    ] & {
      eventTokenId: BigNumber;
      params: BigNumber;
      price: BigNumber;
      supply: BigNumber;
      subscriptionDuration: BigNumber;
      subscriptionActivatedAt: BigNumber;
      tier: BigNumber;
    })[]
  >;

  initialize(
    storageAddress: string,
    chainlinkPriceAggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  prolongSubscription(
    ticketId: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeeCollector(
    newFeeCollector: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setFeeRate(
    newFeeRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSlippageRate(
    newSlippageRate: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenContract(
    tokenContractAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeTo(
    newImplementation: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  upgradeToAndCall(
    newImplementation: string,
    data: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  version(overrides?: CallOverrides): Promise<number>;

  callStatic: {
    INFINITE_SUPPLY_TICKET_BIT(overrides?: CallOverrides): Promise<number>;

    OFFLINE_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<number>;

    ONLINE_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<number>;

    SUBSCRIPTION_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<number>;

    USED_TICKET_BIT(overrides?: CallOverrides): Promise<number>;

    buyTickets(
      ticketId: BigNumberish,
      _for: string,
      overrides?: CallOverrides
    ): Promise<void>;

    commitVerifiedTickets(
      eventTokenId: BigNumberish,
      ticketIds: BigNumberish[],
      owners: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: CallOverrides
    ): Promise<void>;

    getEventManagers(
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getEventTickets(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        eventTokenId: BigNumber;
        params: BigNumber;
        price: BigNumber;
        supply: BigNumber;
        subscriptionDuration: BigNumber;
        subscriptionActivatedAt: BigNumber;
        tier: BigNumber;
      })[][]
    >;

    getEvents(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([string, string, string[], BigNumber[]] & {
        organizer: string;
        beneficiary: string;
        managers: string[];
        ticketIds: BigNumber[];
      })[]
    >;

    getFeeCollector(overrides?: CallOverrides): Promise<string>;

    getFeeRate(overrides?: CallOverrides): Promise<number>;

    getTickets(
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      ([
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ] & {
        eventTokenId: BigNumber;
        params: BigNumber;
        price: BigNumber;
        supply: BigNumber;
        subscriptionDuration: BigNumber;
        subscriptionActivatedAt: BigNumber;
        tier: BigNumber;
      })[]
    >;

    initialize(
      storageAddress: string,
      chainlinkPriceAggregator: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    prolongSubscription(
      ticketId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setFeeCollector(
      newFeeCollector: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setFeeRate(
      newFeeRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setSlippageRate(
      newSlippageRate: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeTo(
      newImplementation: string,
      overrides?: CallOverrides
    ): Promise<void>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    version(overrides?: CallOverrides): Promise<number>;
  };

  filters: {
    "AdminChanged(address,address)"(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    AdminChanged(
      previousAdmin?: null,
      newAdmin?: null
    ): TypedEventFilter<
      [string, string],
      { previousAdmin: string; newAdmin: string }
    >;

    "BeaconUpgraded(address)"(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    BeaconUpgraded(
      beacon?: string | null
    ): TypedEventFilter<[string], { beacon: string }>;

    "EventCreated(uint256,address)"(
      tokenId?: BigNumberish | null,
      organizer?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { tokenId: BigNumber; organizer: string }
    >;

    EventCreated(
      tokenId?: BigNumberish | null,
      organizer?: string | null
    ): TypedEventFilter<
      [BigNumber, string],
      { tokenId: BigNumber; organizer: string }
    >;

    "Initialized(uint8)"(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    Initialized(
      version?: null
    ): TypedEventFilter<[number], { version: number }>;

    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    "TicketBought(uint256,uint256,address)"(
      eventTokenId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { eventTokenId: BigNumber; tokenId: BigNumber; buyer: string }
    >;

    TicketBought(
      eventTokenId?: BigNumberish | null,
      tokenId?: BigNumberish | null,
      buyer?: string | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { eventTokenId: BigNumber; tokenId: BigNumber; buyer: string }
    >;

    "TicketUsed(uint256,uint256,address)"(
      tokenId?: BigNumberish | null,
      eventTokenId?: BigNumberish | null,
      owner?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { tokenId: BigNumber; eventTokenId: BigNumber; owner: string }
    >;

    TicketUsed(
      tokenId?: BigNumberish | null,
      eventTokenId?: BigNumberish | null,
      owner?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { tokenId: BigNumber; eventTokenId: BigNumber; owner: string }
    >;

    "TicketsCreated(uint256,uint256,address)"(
      tokenId?: BigNumberish | null,
      eventTokenId?: BigNumberish | null,
      organizer?: string | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { tokenId: BigNumber; eventTokenId: BigNumber; organizer: string }
    >;

    TicketsCreated(
      tokenId?: BigNumberish | null,
      eventTokenId?: BigNumberish | null,
      organizer?: string | null
    ): TypedEventFilter<
      [BigNumber, BigNumber, string],
      { tokenId: BigNumber; eventTokenId: BigNumber; organizer: string }
    >;

    "Upgraded(address)"(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;

    Upgraded(
      implementation?: string | null
    ): TypedEventFilter<[string], { implementation: string }>;
  };

  estimateGas: {
    INFINITE_SUPPLY_TICKET_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    OFFLINE_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    ONLINE_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    SUBSCRIPTION_TICKET_TYPE_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    USED_TICKET_BIT(overrides?: CallOverrides): Promise<BigNumber>;

    buyTickets(
      ticketId: BigNumberish,
      _for: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    commitVerifiedTickets(
      eventTokenId: BigNumberish,
      ticketIds: BigNumberish[],
      owners: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getEventManagers(
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEventTickets(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getEvents(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getFeeCollector(overrides?: CallOverrides): Promise<BigNumber>;

    getFeeRate(overrides?: CallOverrides): Promise<BigNumber>;

    getTickets(
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      storageAddress: string,
      chainlinkPriceAggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    prolongSubscription(
      ticketId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeeCollector(
      newFeeCollector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setFeeRate(
      newFeeRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSlippageRate(
      newSlippageRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    version(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    INFINITE_SUPPLY_TICKET_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    OFFLINE_TICKET_TYPE_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    ONLINE_TICKET_TYPE_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    SUBSCRIPTION_TICKET_TYPE_BIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    USED_TICKET_BIT(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    buyTickets(
      ticketId: BigNumberish,
      _for: string,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    commitVerifiedTickets(
      eventTokenId: BigNumberish,
      ticketIds: BigNumberish[],
      owners: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createEvent(
      payload: {
        ticketSupply: BigNumberish[];
        ticketPrice: BigNumberish[];
        subscriptionDuration: BigNumberish[];
        params: BigNumberish[];
        beneficiary: string;
        managers: string[];
        eventMetadataUri: string;
        ticketMetadataUri: string[];
      },
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getEventManagers(
      eventId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEventTickets(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getEvents(
      eventIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getFeeCollector(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getFeeRate(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTickets(
      ticketIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      storageAddress: string,
      chainlinkPriceAggregator: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    prolongSubscription(
      ticketId: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeeCollector(
      newFeeCollector: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setFeeRate(
      newFeeRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSlippageRate(
      newSlippageRate: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenContract(
      tokenContractAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      newImplementation: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    upgradeToAndCall(
      newImplementation: string,
      data: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    version(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
